#!/bin/bash

system_path="./out_ext4/system.new.img"
system_dlkm_path="./out_ext4/system_dlkm.new.img"
product_path="./out_ext4/product.new.img"
vendor_path="./out_ext4/vendor.new.img"
vendor_dlkm_path="./out_ext4/vendor_dlkm.new.img"
odm_path="./out_ext4/odm.new.img"
ext_path="./out_ext4/system_ext.new.img"

# Read the size from the text file into a variable
read -r size_from_file < "./orignal_super_size"

echo "-------------------------------"
echo "Super size $size_from_file bytes"
echo "-------------------------------"


threshold_size=$size_from_file


# Function to check if the size is below the threshold
check_size() {
    local total_size=0
    local file_paths=("$@")

    for file_path in "${file_paths[@]}"; do
        local file_size=$(stat -c "%s" "$file_path")
        ((total_size += file_size))
    done

    if ((total_size < threshold_size)); then
        echo "$total_size"
        ./mk_super_ext
    else
        echo "  EXT4 Images cannot fit to Super"
        echo "  You have to do this manually"
        exit 1
    fi
}

echo ""
echo "-------------------------------"
echo "  Size after EXT4"
echo "  system+system_dlkm+product+vendor+vendor_dlkm+odm+system_ext"
echo "-------------------------------"

# Check the sum of sizes
echo "$(check_size "$system_path" "$system_dlkm_path" "$product_path" "$vendor_path" "$vendor_dlkm_path" "$odm_path" "$ext_path") bytes"

echo "-------------------------------"
echo ""

