#!/bin/bash

echo ""
echo "-------------------------------"
echo "  Extracing Super.img        "
echo "-------------------------------"
echo ""

./bin/lpunpack ./rom/super.raw
rm -rf ori > /dev/null 2>&1
rm -rf ./rom/super.raw > /dev/null 2>&1
mkdir ori 
mv system.img ./ori
mv system_ext.img ./ori > /dev/null 2>&1
mv system_dlkm.img ./ori
mv product.img ./ori  
mv odm.img ./ori  
mv vendor.img ./ori
mv vendor_dlkm.img ./ori

./chk_fs
